import { Empreiteira, Obra, PaymentData, UnidadeMedida } from './types';

export const mockObras: Obra[] = [
  {
    id: '4',
    nome: 'Residencial Jardim das Flores',
    descricao: 'Condomínio de casas geminadas',
    dataInicio: '2024-04-20',
    tarefas: [
      {
        id: '4-1',
        local: { id: '1', name: 'Fundação' },
        atividade: 'Escavação e concretagem',
        unidade: 'm³',
        quantidade: 150,
        valor: 22500,
        empreiteira: 'Concretar Engenharia',
        statusPagamento: 'pago',
        statusMedicao: 'medido',
        dataLimite: '2024-05-10',
        dataCriacao: '2024-03-22',
      },
      {
        id: '4-2',
        local: { id: '2', name: 'Estrutura' },
        atividade: 'Levantamento de pilares',
        unidade: 'unidade',
        quantidade: 20,
        valor: 18000,
        empreiteira: 'Estruturas Forte',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
        dataLimite: '2024-05-10',
        dataCriacao: '2024-03-20',
      },
      {
        id: '4-3',
        local: { id: '3', name: 'Cobertura' },
        atividade: 'Instalação de telhado cerâmico',
        unidade: 'm²',
        quantidade: 350,
        valor: 24500,
        empreiteira: 'Telhas Brasil',
        statusPagamento: 'pendente',
        statusMedicao: 'medido',
        dataLimite: '2024-05-10',
        dataCriacao: '2024-04-20',
      },
      {
        id: '4-4',
        local: { id: '4', name: 'Instalações' },
        atividade: 'Rede hidráulica',
        unidade: 'ponto',
        quantidade: 40,
        valor: 8000,
        empreiteira: 'Hidro Center',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
        dataLimite: '2024-05-10',
        dataCriacao: '2024-03-20',
      },
      {
        id: '4-5',
        local: { id: '5', name: 'Instalações' },
        atividade: 'Rede elétrica',
        unidade: 'ponto',
        quantidade: 60,
        valor: 12000,
        empreiteira: 'Eletro Master',
        statusPagamento: 'pendente',
        statusMedicao: 'retencao',
      },
      {
        id: '4-6',
        local: { id: '6', name: 'Acabamento interno' },
        atividade: 'Pintura geral',
        unidade: 'm²',
        quantidade: 400,
        valor: 16000,
        empreiteira: 'Tintas & Cia',
        statusPagamento: 'atrasado',
        statusMedicao: 'medido',
      },
      {
        id: '4-7',
        local: { id: '7', name: 'Acabamento interno' },
        atividade: 'Assentamento de piso porcelanato',
        unidade: 'm²',
        quantidade: 250,
        valor: 22500,
        empreiteira: 'Pisos Premium',
        statusPagamento: 'pago',
        statusMedicao: 'retencao',
      },
      {
        id: '4-8',
        local: { id: '8', name: 'Área comum' },
        atividade: 'Paisagismo',
        unidade: 'm²',
        quantidade: 180,
        valor: 10800,
        empreiteira: 'Verde Vida',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
      },
      {
        id: '4-9',
        local: { id: '9', name: 'Garagem' },
        atividade: 'Pavimentação',
        unidade: 'm²',
        quantidade: 200,
        valor: 16000,
        empreiteira: 'Asfaltos União',
        statusPagamento: 'pendente',
        statusMedicao: 'medido',
      },
      {
        id: '4-10',
        local: { id: '10', name: 'Portaria' },
        atividade: 'Instalação de portão eletrônico',
        unidade: 'unidade',
        quantidade: 1,
        valor: 7500,
        empreiteira: 'SegPort Tech',
        statusPagamento: 'pago',
        statusMedicao: 'retencao',
      },
    ],
  },
  {
    id: '5',
    nome: 'Hospital Municipal Vida Nova',
    descricao: 'Construção de hospital de médio porte',
    dataInicio: '2024-05-10',
    tarefas: [
      {
        id: '5-1',
        local: { id: '1', name: 'Fundação' },
        atividade: 'Estacas pré-moldadas',
        unidade: 'm',
        quantidade: 500,
        valor: 75000,
        empreiteira: 'Fundatec',
        statusPagamento: 'pago',
        statusMedicao: 'medido',
      },
      {
        id: '5-2',
        local: { id: '2', name: 'Estrutura' },
        atividade: 'Concretagem de lajes',
        unidade: 'm²',
        quantidade: 1000,
        valor: 95000,
        empreiteira: 'Concretar Engenharia',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
      },
      {
        id: '5-3',
        local: { id: '3', name: 'Estrutura' },
        atividade: 'Colocação de vigas metálicas',
        unidade: 'ton',
        quantidade: 20,
        valor: 180000,
        empreiteira: 'Metal Forte',
        statusPagamento: 'pendente',
        statusMedicao: 'medido',
      },
      {
        id: '5-4',
        local: { id: '4', name: 'Cobertura' },
        atividade: 'Telhado metálico',
        unidade: 'm²',
        quantidade: 800,
        valor: 64000,
        empreiteira: 'CobreBem',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
      },
      {
        id: '5-5',
        local: { id: '5', name: 'Instalações' },
        atividade: 'Rede de gases hospitalares',
        unidade: 'ponto',
        quantidade: 50,
        valor: 50000,
        empreiteira: 'HospGases Ltda',
        statusPagamento: 'pendente',
        statusMedicao: 'medido',
      },
      {
        id: '5-6',
        local: { id: '6', name: 'Instalações' },
        atividade: 'Rede elétrica hospitalar',
        unidade: 'ponto',
        quantidade: 200,
        valor: 40000,
        empreiteira: 'Eletro Master',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
      },
      {
        id: '5-7',
        local: { id: '7', name: 'Acabamento interno' },
        atividade: 'Piso vinílico antiestático',
        unidade: 'm²',
        quantidade: 1500,
        valor: 135000,
        empreiteira: 'Pisos Premium',
        statusPagamento: 'pendente',
        statusMedicao: 'medido',
      },
      {
        id: '5-8',
        local: { id: '8', name: 'Acabamento interno' },
        atividade: 'Forro acústico',
        unidade: 'm²',
        quantidade: 1200,
        valor: 96000,
        empreiteira: 'Acústica Total',
        statusPagamento: 'pago',
        statusMedicao: 'medido',
      },
      {
        id: '5-9',
        local: { id: '9', name: 'Acabamento interno' },
        atividade: 'Pintura epóxi',
        unidade: 'm²',
        quantidade: 900,
        valor: 54000,
        empreiteira: 'Tintas & Cia',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
      },
      {
        id: '5-10',
        local: { id: '10', name: 'Ambulatório' },
        atividade: 'Divisórias hospitalares',
        unidade: 'm²',
        quantidade: 400,
        valor: 32000,
        empreiteira: 'HospConstrutora',
        statusPagamento: 'pendente',
        statusMedicao: 'medido',
      },
      {
        id: '5-11',
        local: { id: '11', name: 'Enfermarias' },
        atividade: 'Instalação de camas hospitalares',
        unidade: 'unidade',
        quantidade: 120,
        valor: 240000,
        empreiteira: 'MediTech',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
      },
      {
        id: '5-12',
        local: { id: '12', name: 'UTI' },
        atividade: 'Instalação de monitores cardíacos',
        unidade: 'unidade',
        quantidade: 40,
        valor: 400000,
        empreiteira: 'CardioLife',
        statusPagamento: 'pendente',
        statusMedicao: 'medido',
      },
      {
        id: '5-13',
        local: { id: '13', name: 'Centro Cirúrgico' },
        atividade: 'Montagem de salas cirúrgicas',
        unidade: 'unidade',
        quantidade: 5,
        valor: 500000,
        empreiteira: 'CirurgiTech',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
      },
      {
        id: '5-14',
        local: { id: '14', name: 'Laboratório' },
        atividade: 'Instalação de bancadas inox',
        unidade: 'm²',
        quantidade: 200,
        valor: 60000,
        empreiteira: 'Inox Prime',
        statusPagamento: 'pago',
        statusMedicao: 'medido',
      },
      {
        id: '5-15',
        local: { id: '15', name: 'Recepção' },
        atividade: 'Montagem de balcão de atendimento',
        unidade: 'unidade',
        quantidade: 1,
        valor: 15000,
        empreiteira: 'Moveis Hospitalares',
        statusPagamento: 'pendente',
        statusMedicao: 'medido',
      },
      {
        id: '5-16',
        local: { id: '16', name: 'Refeitório' },
        atividade: 'Instalação de cozinha industrial',
        unidade: 'unidade',
        quantidade: 1,
        valor: 180000,
        empreiteira: 'CozinTec',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
      },
      {
        id: '5-17',
        local: { id: '17', name: 'Estacionamento' },
        atividade: 'Pavimentação asfáltica',
        unidade: 'm²',
        quantidade: 3000,
        valor: 240000,
        empreiteira: 'Asfaltos União',
        statusPagamento: 'pendente',
        statusMedicao: 'medido',
      },
      {
        id: '5-18',
        local: { id: '18', name: 'Áreas externas' },
        atividade: 'Paisagismo completo',
        unidade: 'm²',
        quantidade: 1000,
        valor: 60000,
        empreiteira: 'Verde Vida',
        statusPagamento: 'pago',
        statusMedicao: 'medido',
      },
      {
        id: '5-19',
        local: { id: '19', name: 'Segurança' },
        atividade: 'Instalação de câmeras CFTV',
        unidade: 'unidade',
        quantidade: 60,
        valor: 90000,
        empreiteira: 'SegPort Tech',
        statusPagamento: 'pendente',
        statusMedicao: 'medido',
      },
      {
        id: '5-20',
        local: { id: '20', name: 'Portaria' },
        atividade: 'Controle de acesso biométrico',
        unidade: 'unidade',
        quantidade: 4,
        valor: 40000,
        empreiteira: 'BioAccess Ltda',
        statusPagamento: 'em_andamento',
        statusMedicao: 'em_andamento',
      },
    ],
  },
];

export const mockRelatorio: PaymentData[] = [
  {
    id: 1,
    local: 'Obra Centro',
    atividade: 'Fundação',
    unidade: 'm³',
    quantidade: 150,
    valor: 45000.0,
    empreiteira: 'Construtora Alpha',
    dataLimite: '2024-01-15',
    dataPagamento: '2024-01-12',
    usuarioResponsavel: 'João Silva',
    status: 'pago',
  },
  {
    id: 2,
    local: 'Obra Norte',
    atividade: 'Estrutura',
    unidade: 'm²',
    quantidade: 200,
    valor: 80000.0,
    empreiteira: 'Construtora Beta',
    dataLimite: '2024-01-20',
    dataPagamento: '2024-01-18',
    usuarioResponsavel: 'Maria Santos',
    status: 'pago',
  },
  {
    id: 3,
    local: 'Obra Sul',
    atividade: 'Alvenaria',
    unidade: 'm²',
    quantidade: 300,
    valor: 60000.0,
    empreiteira: 'Construtora Gamma',
    dataLimite: '2024-01-25',
    dataPagamento: '2024-01-23',
    usuarioResponsavel: 'Pedro Costa',
    status: 'pago',
  },
  {
    id: 4,
    local: 'Obra Leste',
    atividade: 'Cobertura',
    unidade: 'm²',
    quantidade: 120,
    valor: 35000.0,
    empreiteira: 'Construtora Delta',
    dataLimite: '2024-02-01',
    dataPagamento: '2024-01-30',
    usuarioResponsavel: 'Ana Lima',
    status: 'pago',
  },
  {
    id: 5,
    local: 'Obra Oeste',
    atividade: 'Acabamento',
    unidade: 'm²',
    quantidade: 250,
    valor: 75000.0,
    empreiteira: 'Construtora Epsilon',
    dataLimite: '2024-02-05',
    dataPagamento: '2024-02-03',
    usuarioResponsavel: 'Carlos Ferreira',
    status: 'pago',
  },
  {
    id: 6,
    local: 'Obra Centro',
    atividade: 'Instalações',
    unidade: 'un',
    quantidade: 50,
    valor: 25000.0,
    empreiteira: 'Construtora Alpha',
    dataLimite: '2024-02-10',
    dataPagamento: '2024-02-08',
    usuarioResponsavel: 'João Silva',
    status: 'pago',
  },
  {
    id: 7,
    local: 'Obra Norte',
    atividade: 'Pintura',
    unidade: 'm²',
    quantidade: 400,
    valor: 20000.0,
    empreiteira: 'Construtora Beta',
    dataLimite: '2024-02-15',
    dataPagamento: '2024-02-12',
    usuarioResponsavel: 'Maria Santos',
    status: 'pago',
  },
  {
    id: 8,
    local: 'Obra Sul',
    atividade: 'Paisagismo',
    unidade: 'm²',
    quantidade: 100,
    valor: 15000.0,
    empreiteira: 'Construtora Gamma',
    dataLimite: '2024-02-20',
    dataPagamento: '2024-02-18',
    usuarioResponsavel: 'Pedro Costa',
    status: 'pago',
  },
];

export const mockLocais = [
  { id: '1', name: 'Fundação' },
  { id: '2', name: 'Estrutura' },
  { id: '3', name: 'Cobertura' },
  { id: '4', name: 'Instalações' },
  { id: '5', name: 'Acabamento interno' },
  { id: '6', name: 'Área comum' },
  { id: '7', name: 'Garagem' },
  { id: '8', name: 'Portaria' },
  { id: '9', name: 'Ambulatório' },
  { id: '10', name: 'Enfermarias' },
  { id: '11', name: 'UTI' },
  { id: '12', name: 'Centro Cirúrgico' },
  { id: '13', name: 'Laboratório' },
  { id: '14', name: 'Recepção' },
  { id: '15', name: 'Refeitório' },
  { id: '16', name: 'Estacionamento' },
  { id: '17', name: 'Áreas externas' },
  { id: '18', name: 'Segurança' },
];

export const mockContractors: Empreiteira[] = [
  {
    id: 1,
    descricao: 'Especializada em fundações e terraplanagem',
    nome: 'SoloFirme',
    createdAt: '2024-02-01',
  },
  {
    id: 2,
    descricao: 'Serviços de alvenaria estrutural e acabamentos',
    nome: 'Constrular',
    createdAt: '2024-02-02',
  },
  {
    id: 3,
    descricao: 'Instalações elétricas prediais e industriais',
    nome: 'EletroMax',
    createdAt: '2024-02-03',
  },
  {
    id: 4,
    descricao: 'Tubulações hidráulicas e sistemas de esgoto',
    nome: 'Hidrosul',
    createdAt: '2024-02-04',
  },
  {
    id: 5,
    descricao: 'Montagem de estruturas metálicas e soldagem',
    nome: 'MetalAr',
    createdAt: '2024-02-05',
  },
  {
    id: 6,
    descricao: 'Revestimentos cerâmicos, pisos e azulejos',
    nome: 'RevestLar',
    createdAt: '2024-02-06',
  },
  {
    id: 7,
    descricao: 'Serviços de pintura residencial e predial',
    nome: 'Pintart',
    createdAt: '2024-02-07',
  },
  {
    id: 8,
    descricao: 'Instalação de vidros temperados e esquadrias',
    nome: 'VidroReal',
    createdAt: '2024-02-08',
  },
];

export const mockUnits: UnidadeMedida[] = [
  {
    id: 1,
    descricao: 'Metro Quadrado',
    complemento: 'm²',
    createdAt: '2024-01-15',
  },
  {
    id: 2,
    descricao: 'Metro Cúbico',
    complemento: 'm³',
    createdAt: '2024-01-16',
  },
  {
    id: 3,
    descricao: 'Quilograma',
    complemento: 'kg',
    createdAt: '2024-01-17',
  },
  {
    id: 4,
    descricao: 'Quilômetro',
    complemento: 'km',
    createdAt: '2024-01-18',
  },
  {
    id: 5,
    descricao: 'Metro Linear',
    complemento: 'm',
    createdAt: '2024-01-19',
  },
  {
    id: 6,
    descricao: 'Litro',
    complemento: 'l',
    createdAt: '2024-01-20',
  },
  {
    id: 7,
    descricao: 'Unidade',
    complemento: 'un',
    createdAt: '2024-01-21',
  },
  {
    id: 8,
    descricao: 'Tonelada',
    complemento: 't',
    createdAt: '2024-01-22',
  },
];
