import { Empreiteira, Obra, PaymentData, UnidadeMedida } from './types';

export const mockObras: Obra[] = [
  {
    id: '4',
    name: 'Residencial Jardim das Flores',
    description: 'Condomínio de casas geminadas',
    dataInicio: '2024-04-20',
    tarefas: [
      {
        id: '4-1',
        location: { id: '1', name: 'Fundação' },
        activity: 'Escavação e concretagem',
        unitOfMeasure: 'm³',
        quantity: 150,
        totalAmount: 22500,
        contractor: 'Concretar Engenharia',
        paymentStatus: 'pago',
        measurementStatus: 'medido',
        dataLimite: '2024-05-10',
        createdAt: '2024-03-22',
      },
      {
        id: '4-2',
        location: { id: '2', name: 'Estrutura' },
        activity: 'Levantamento de pilares',
        unitOfMeasure: 'unidade',
        quantity: 20,
        totalAmount: 18000,
        contractor: 'Estruturas Forte',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
        dataLimite: '2024-05-10',
        createdAt: '2024-03-20',
      },
      {
        id: '4-3',
        location: { id: '3', name: 'Cobertura' },
        activity: 'Instalação de telhado cerâmico',
        unitOfMeasure: 'm²',
        quantity: 350,
        totalAmount: 24500,
        contractor: 'Telhas Brasil',
        paymentStatus: 'pendente',
        measurementStatus: 'medido',
        dataLimite: '2024-05-10',
        createdAt: '2024-04-20',
      },
      {
        id: '4-4',
        location: { id: '4', name: 'Instalações' },
        activity: 'Rede hidráulica',
        unitOfMeasure: 'ponto',
        quantity: 40,
        totalAmount: 8000,
        contractor: 'Hidro Center',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
        dataLimite: '2024-05-10',
        createdAt: '2024-03-20',
      },
      {
        id: '4-5',
        location: { id: '5', name: 'Instalações' },
        activity: 'Rede elétrica',
        unitOfMeasure: 'ponto',
        quantity: 60,
        totalAmount: 12000,
        contractor: 'Eletro Master',
        paymentStatus: 'pendente',
        measurementStatus: 'retencao',
      },
      {
        id: '4-6',
        location: { id: '6', name: 'Acabamento interno' },
        activity: 'Pintura geral',
        unitOfMeasure: 'm²',
        quantity: 400,
        totalAmount: 16000,
        contractor: 'Tintas & Cia',
        paymentStatus: 'atrasado',
        measurementStatus: 'medido',
      },
      {
        id: '4-7',
        location: { id: '7', name: 'Acabamento interno' },
        activity: 'Assentamento de piso porcelanato',
        unitOfMeasure: 'm²',
        quantity: 250,
        totalAmount: 22500,
        contractor: 'Pisos Premium',
        paymentStatus: 'pago',
        measurementStatus: 'retencao',
      },
      {
        id: '4-8',
        location: { id: '8', name: 'Área comum' },
        activity: 'Paisagismo',
        unitOfMeasure: 'm²',
        quantity: 180,
        totalAmount: 10800,
        contractor: 'Verde Vida',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
      },
      {
        id: '4-9',
        location: { id: '9', name: 'Garagem' },
        activity: 'Pavimentação',
        unitOfMeasure: 'm²',
        quantity: 200,
        totalAmount: 16000,
        contractor: 'Asfaltos União',
        paymentStatus: 'pendente',
        measurementStatus: 'medido',
      },
      {
        id: '4-10',
        location: { id: '10', name: 'Portaria' },
        activity: 'Instalação de portão eletrônico',
        unitOfMeasure: 'unidade',
        quantity: 1,
        totalAmount: 7500,
        contractor: 'SegPort Tech',
        paymentStatus: 'pago',
        measurementStatus: 'retencao',
      },
    ],
  },
  {
    id: '5',
    name: 'Hospital Municipal Vida Nova',
    description: 'Construção de hospital de médio porte',
    dataInicio: '2024-05-10',
    tarefas: [
      {
        id: '5-1',
        location: { id: '1', name: 'Fundação' },
        activity: 'Estacas pré-moldadas',
        unitOfMeasure: 'm',
        quantity: 500,
        totalAmount: 75000,
        contractor: 'Fundatec',
        paymentStatus: 'pago',
        measurementStatus: 'medido',
      },
      {
        id: '5-2',
        location: { id: '2', name: 'Estrutura' },
        activity: 'Concretagem de lajes',
        unitOfMeasure: 'm²',
        quantity: 1000,
        totalAmount: 95000,
        contractor: 'Concretar Engenharia',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
      },
      {
        id: '5-3',
        location: { id: '3', name: 'Estrutura' },
        activity: 'Colocação de vigas metálicas',
        unitOfMeasure: 'ton',
        quantity: 20,
        totalAmount: 180000,
        contractor: 'Metal Forte',
        paymentStatus: 'pendente',
        measurementStatus: 'medido',
      },
      {
        id: '5-4',
        location: { id: '4', name: 'Cobertura' },
        activity: 'Telhado metálico',
        unitOfMeasure: 'm²',
        quantity: 800,
        totalAmount: 64000,
        contractor: 'CobreBem',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
      },
      {
        id: '5-5',
        location: { id: '5', name: 'Instalações' },
        activity: 'Rede de gases hospitalares',
        unitOfMeasure: 'ponto',
        quantity: 50,
        totalAmount: 50000,
        contractor: 'HospGases Ltda',
        paymentStatus: 'pendente',
        measurementStatus: 'medido',
      },
      {
        id: '5-6',
        location: { id: '6', name: 'Instalações' },
        activity: 'Rede elétrica hospitalar',
        unitOfMeasure: 'ponto',
        quantity: 200,
        totalAmount: 40000,
        contractor: 'Eletro Master',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
      },
      {
        id: '5-7',
        location: { id: '7', name: 'Acabamento interno' },
        activity: 'Piso vinílico antiestático',
        unitOfMeasure: 'm²',
        quantity: 1500,
        totalAmount: 135000,
        contractor: 'Pisos Premium',
        paymentStatus: 'pendente',
        measurementStatus: 'medido',
      },
      {
        id: '5-8',
        location: { id: '8', name: 'Acabamento interno' },
        activity: 'Forro acústico',
        unitOfMeasure: 'm²',
        quantity: 1200,
        totalAmount: 96000,
        contractor: 'Acústica Total',
        paymentStatus: 'pago',
        measurementStatus: 'medido',
      },
      {
        id: '5-9',
        location: { id: '9', name: 'Acabamento interno' },
        activity: 'Pintura epóxi',
        unitOfMeasure: 'm²',
        quantity: 900,
        totalAmount: 54000,
        contractor: 'Tintas & Cia',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
      },
      {
        id: '5-10',
        location: { id: '10', name: 'Ambulatório' },
        activity: 'Divisórias hospitalares',
        unitOfMeasure: 'm²',
        quantity: 400,
        totalAmount: 32000,
        contractor: 'HospConstrutora',
        paymentStatus: 'pendente',
        measurementStatus: 'medido',
      },
      {
        id: '5-11',
        location: { id: '11', name: 'Enfermarias' },
        activity: 'Instalação de camas hospitalares',
        unitOfMeasure: 'unidade',
        quantity: 120,
        totalAmount: 240000,
        contractor: 'MediTech',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
      },
      {
        id: '5-12',
        location: { id: '12', name: 'UTI' },
        activity: 'Instalação de monitores cardíacos',
        unitOfMeasure: 'unidade',
        quantity: 40,
        totalAmount: 400000,
        contractor: 'CardioLife',
        paymentStatus: 'pendente',
        measurementStatus: 'medido',
      },
      {
        id: '5-13',
        location: { id: '13', name: 'Centro Cirúrgico' },
        activity: 'Montagem de salas cirúrgicas',
        unitOfMeasure: 'unidade',
        quantity: 5,
        totalAmount: 500000,
        contractor: 'CirurgiTech',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
      },
      {
        id: '5-14',
        location: { id: '14', name: 'Laboratório' },
        activity: 'Instalação de bancadas inox',
        unitOfMeasure: 'm²',
        quantity: 200,
        totalAmount: 60000,
        contractor: 'Inox Prime',
        paymentStatus: 'pago',
        measurementStatus: 'medido',
      },
      {
        id: '5-15',
        location: { id: '15', name: 'Recepção' },
        activity: 'Montagem de balcão de atendimento',
        unitOfMeasure: 'unidade',
        quantity: 1,
        totalAmount: 15000,
        contractor: 'Moveis Hospitalares',
        paymentStatus: 'pendente',
        measurementStatus: 'medido',
      },
      {
        id: '5-16',
        location: { id: '16', name: 'Refeitório' },
        activity: 'Instalação de cozinha industrial',
        unitOfMeasure: 'unidade',
        quantity: 1,
        totalAmount: 180000,
        contractor: 'CozinTec',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
      },
      {
        id: '5-17',
        location: { id: '17', name: 'Estacionamento' },
        activity: 'Pavimentação asfáltica',
        unitOfMeasure: 'm²',
        quantity: 3000,
        totalAmount: 240000,
        contractor: 'Asfaltos União',
        paymentStatus: 'pendente',
        measurementStatus: 'medido',
      },
      {
        id: '5-18',
        location: { id: '18', name: 'Áreas externas' },
        activity: 'Paisagismo completo',
        unitOfMeasure: 'm²',
        quantity: 1000,
        totalAmount: 60000,
        contractor: 'Verde Vida',
        paymentStatus: 'pago',
        measurementStatus: 'medido',
      },
      {
        id: '5-19',
        location: { id: '19', name: 'Segurança' },
        activity: 'Instalação de câmeras CFTV',
        unitOfMeasure: 'unidade',
        quantity: 60,
        totalAmount: 90000,
        contractor: 'SegPort Tech',
        paymentStatus: 'pendente',
        measurementStatus: 'medido',
      },
      {
        id: '5-20',
        location: { id: '20', name: 'Portaria' },
        activity: 'Controle de acesso biométrico',
        unitOfMeasure: 'unidade',
        quantity: 4,
        totalAmount: 40000,
        contractor: 'BioAccess Ltda',
        paymentStatus: 'em_andamento',
        measurementStatus: 'em_andamento',
      },
    ],
  },
];

export const mockRelatorio: PaymentData[] = [
  {
    id: 1,
    local: 'Obra Centro',
    atividade: 'Fundação',
    unidade: 'm³',
    quantidade: 150,
    valor: 45000.0,
    empreiteira: 'Construtora Alpha',
    dataLimite: '2024-01-15',
    dataPagamento: '2024-01-12',
    usuarioResponsavel: 'João Silva',
    status: 'pago',
  },
  {
    id: 2,
    local: 'Obra Norte',
    atividade: 'Estrutura',
    unidade: 'm²',
    quantidade: 200,
    valor: 80000.0,
    empreiteira: 'Construtora Beta',
    dataLimite: '2024-01-20',
    dataPagamento: '2024-01-18',
    usuarioResponsavel: 'Maria Santos',
    status: 'pago',
  },
  {
    id: 3,
    local: 'Obra Sul',
    atividade: 'Alvenaria',
    unidade: 'm²',
    quantidade: 300,
    valor: 60000.0,
    empreiteira: 'Construtora Gamma',
    dataLimite: '2024-01-25',
    dataPagamento: '2024-01-23',
    usuarioResponsavel: 'Pedro Costa',
    status: 'pago',
  },
  {
    id: 4,
    local: 'Obra Leste',
    atividade: 'Cobertura',
    unidade: 'm²',
    quantidade: 120,
    valor: 35000.0,
    empreiteira: 'Construtora Delta',
    dataLimite: '2024-02-01',
    dataPagamento: '2024-01-30',
    usuarioResponsavel: 'Ana Lima',
    status: 'pago',
  },
  {
    id: 5,
    local: 'Obra Oeste',
    atividade: 'Acabamento',
    unidade: 'm²',
    quantidade: 250,
    valor: 75000.0,
    empreiteira: 'Construtora Epsilon',
    dataLimite: '2024-02-05',
    dataPagamento: '2024-02-03',
    usuarioResponsavel: 'Carlos Ferreira',
    status: 'pago',
  },
  {
    id: 6,
    local: 'Obra Centro',
    atividade: 'Instalações',
    unidade: 'un',
    quantidade: 50,
    valor: 25000.0,
    empreiteira: 'Construtora Alpha',
    dataLimite: '2024-02-10',
    dataPagamento: '2024-02-08',
    usuarioResponsavel: 'João Silva',
    status: 'pago',
  },
  {
    id: 7,
    local: 'Obra Norte',
    atividade: 'Pintura',
    unidade: 'm²',
    quantidade: 400,
    valor: 20000.0,
    empreiteira: 'Construtora Beta',
    dataLimite: '2024-02-15',
    dataPagamento: '2024-02-12',
    usuarioResponsavel: 'Maria Santos',
    status: 'pago',
  },
  {
    id: 8,
    local: 'Obra Sul',
    atividade: 'Paisagismo',
    unidade: 'm²',
    quantidade: 100,
    valor: 15000.0,
    empreiteira: 'Construtora Gamma',
    dataLimite: '2024-02-20',
    dataPagamento: '2024-02-18',
    usuarioResponsavel: 'Pedro Costa',
    status: 'pago',
  },
];

export const mockLocais = [
  { id: '1', name: 'Fundação' },
  { id: '2', name: 'Estrutura' },
  { id: '3', name: 'Cobertura' },
  { id: '4', name: 'Instalações' },
  { id: '5', name: 'Acabamento interno' },
  { id: '6', name: 'Área comum' },
  { id: '7', name: 'Garagem' },
  { id: '8', name: 'Portaria' },
  { id: '9', name: 'Ambulatório' },
  { id: '10', name: 'Enfermarias' },
  { id: '11', name: 'UTI' },
  { id: '12', name: 'Centro Cirúrgico' },
  { id: '13', name: 'Laboratório' },
  { id: '14', name: 'Recepção' },
  { id: '15', name: 'Refeitório' },
  { id: '16', name: 'Estacionamento' },
  { id: '17', name: 'Áreas externas' },
  { id: '18', name: 'Segurança' },
];

export const mockContractors: Empreiteira[] = [
  {
    id: 1,
    descricao: 'Especializada em fundações e terraplanagem',
    nome: 'SoloFirme',
    createdAt: '2024-02-01',
  },
  {
    id: 2,
    descricao: 'Serviços de alvenaria estrutural e acabamentos',
    nome: 'Constrular',
    createdAt: '2024-02-02',
  },
  {
    id: 3,
    descricao: 'Instalações elétricas prediais e industriais',
    nome: 'EletroMax',
    createdAt: '2024-02-03',
  },
  {
    id: 4,
    descricao: 'Tubulações hidráulicas e sistemas de esgoto',
    nome: 'Hidrosul',
    createdAt: '2024-02-04',
  },
  {
    id: 5,
    descricao: 'Montagem de estruturas metálicas e soldagem',
    nome: 'MetalAr',
    createdAt: '2024-02-05',
  },
  {
    id: 6,
    descricao: 'Revestimentos cerâmicos, pisos e azulejos',
    nome: 'RevestLar',
    createdAt: '2024-02-06',
  },
  {
    id: 7,
    descricao: 'Serviços de pintura residencial e predial',
    nome: 'Pintart',
    createdAt: '2024-02-07',
  },
  {
    id: 8,
    descricao: 'Instalação de vidros temperados e esquadrias',
    nome: 'VidroReal',
    createdAt: '2024-02-08',
  },
];

export const mockUnits: UnidadeMedida[] = [
  {
    id: 1,
    descricao: 'Metro Quadrado',
    complemento: 'm²',
    createdAt: '2024-01-15',
  },
  {
    id: 2,
    descricao: 'Metro Cúbico',
    complemento: 'm³',
    createdAt: '2024-01-16',
  },
  {
    id: 3,
    descricao: 'Quilograma',
    complemento: 'kg',
    createdAt: '2024-01-17',
  },
  {
    id: 4,
    descricao: 'Quilômetro',
    complemento: 'km',
    createdAt: '2024-01-18',
  },
  {
    id: 5,
    descricao: 'Metro Linear',
    complemento: 'm',
    createdAt: '2024-01-19',
  },
  {
    id: 6,
    descricao: 'Litro',
    complemento: 'l',
    createdAt: '2024-01-20',
  },
  {
    id: 7,
    descricao: 'Unidade',
    complemento: 'un',
    createdAt: '2024-01-21',
  },
  {
    id: 8,
    descricao: 'Tonelada',
    complemento: 't',
    createdAt: '2024-01-22',
  },
];
