import { Obra } from './types';

export const mockObras: Obra[] = [
  {
    id: '1',
    nome: 'Edifício Residencial Aurora',
    descricao: 'Construção de prédio residencial com 15 andares',
    dataInicio: '2024-01-15',
    tarefas: [
      {
        id: '1-1',
        local: 'Térreo - Hall Principal',
        atividade: 'Instalação de piso cerâmico',
        unidade: 'm²',
        quantidade: 120,
        valor: 15600,
        empreiteira: 'Cerâmica Silva Ltda',
        status: 'concluida',
      },
      {
        id: '1-2',
        local: '1º Andar - Apartamento 101',
        atividade: 'Pintura das paredes',
        unidade: 'm²',
        quantidade: 85,
        valor: 2550,
        empreiteira: 'Tintas & Cia',
        status: 'em_andamento',
      },
      {
        id: '1-3',
        local: 'Cobertura',
        atividade: 'Impermeabilização',
        unidade: 'm²',
        quantidade: 200,
        valor: 8000,
        empreiteira: 'Impertech Solutions',
        status: 'pendente',
      },
    ],
  },
  {
    id: '2',
    nome: 'Casa Moderna Jardins',
    descricao: 'Construção de casa de alto padrão',
    dataInicio: '2024-02-01',
    tarefas: [
      {
        id: '2-1',
        local: 'Área Externa',
        atividade: 'Paisagismo completo',
        unidade: 'm²',
        quantidade: 300,
        valor: 18000,
        empreiteira: 'Verde Vida Paisagismo',
        status: 'atrasada',
      },
      {
        id: '2-2',
        local: 'Sala Principal',
        atividade: 'Instalação de forro de gesso',
        unidade: 'm²',
        quantidade: 45,
        valor: 2700,
        empreiteira: 'Gesso Art',
        status: 'em_andamento',
      },
    ],
  },
  {
    id: '3',
    nome: 'Centro Comercial Plaza',
    descricao: 'Complexo comercial com 3 blocos',
    dataInicio: '2024-03-10',
    tarefas: [
      {
        id: '3-1',
        local: 'Bloco A - Loja 05',
        atividade: 'Instalação elétrica',
        unidade: 'ponto',
        quantidade: 45,
        valor: 6750,
        empreiteira: 'Eletro Master',
        status: 'pendente',
      },
      {
        id: '3-2',
        local: 'Estacionamento',
        atividade: 'Demarcação de vagas',
        unidade: 'unidade',
        quantidade: 150,
        valor: 4500,
        empreiteira: 'Sinaliza Bem',
        status: 'concluida',
      },
      {
        id: '3-3',
        local: 'Fachada Principal',
        atividade: 'Aplicação de revestimento ACM',
        unidade: 'm²',
        quantidade: 180,
        valor: 25200,
        empreiteira: 'Fachadas Premium',
        status: 'em_andamento',
      },
    ],
  },
];
